### ISSUE TITLE
list file or block volumes above 50 infinitely loops

### ISSUE THREAD

**Issue by jack-evans** [softlayer/softlayer-cli#5] opened 2023-12-04 16:02 UTC
There appears to be an infinite loop in listing file or block volumes above 50...

I have over 100+ file and 100+ block volumes in IBM cloud dal10 and when I run

```bash
ibmcloud sl file volume-list -d dal10
```

it hangs.

running with `IBMCLOUD_TRACE=true` I can see that it infinitely just increases the offset, with the highest offset I got to was 23550

It looks to be this chunk of coded https://github.com/softlayer/softlayer-cli/blob/master/plugin/managers/storage.go#L344-L356 and is also present further down when its file https://github.com/softlayer/softlayer-cli/blob/master/plugin/managers/storage.go#L385-L397

**Comment by allmightyspiff** [comment] 2023-12-04 16:35
Thanks for letting me know. At first glance I THINK this might be a problem with the API. Specifically when you request a specific datacenter.

It looks like the resultLimit is being ignored when a datacenter is in the object filter, and so just all the results are returned, which is why the exit clause never triggers in that loop.

### Limit = 5, filtering on a datacenter
![image](https://github.com/softlayer/softlayer-cli/assets/7408017/ef11b097-300b-456a-8634-13dc890a9b42)

### Limit = 5, normal filter
![image](https://github.com/softlayer/softlayer-cli/assets/7408017/782f15f2-a8e6-4dbe-a620-fab08e3040fa)


I'm not sure how feasible it is, but removing the `-d dal10` would get the command to work normally for now, while I investigate/escalate this issue internally.

**Comment by allmightyspiff** [comment] 2023-12-04 16:54
Also, did this only start happening recently? If you noticed a specific date where this command broke, that would help me narrow down where the issue is. Thanks

**Comment by allmightyspiff** [comment] 2023-12-04 20:33
turns out this is a somewhat old bug with this specific API call. I'll create at least a work around so you can get all the volumes for a specific DC without the command running in a forever loop though. Will be in the next version 1.5.0

**Comment by allmightyspiff** [comment] 2024-01-02 19:12
Should be fixed now in https://github.com/softlayer/softlayer-cli/releases/tag/v1.5.0

**Closed as completed by allmightyspiff** 2024-01-02 19:12 UTC
Labels: bug
